version: '3.8'
services:
  backend:
    image: gcr.io/kowan-final-project/quote-generator:latest
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - backend
    labels:
      kompose.service.type: LoadBalancer

  postgres:
    image: postgres:14.5-alpine3.16
    restart: always
    environment:
      - POSTGRES_DB=quote_generator
      - POSTGRES_USER=rafi
      - POSTGRES_PASSWORD=passwordforquotegenerator
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    networks:
      - backend
volumes:
  postgres:
networks:
  backend:
  frontend:
