version: '3.8'
services:
  postgres:
    image: postgres:14.5-alpine3.16
    restart: always
    environment:
      - POSTGRES_DB=quote_generator
      - POSTGRES_USER=rafi
      - POSTGRES_PASSWORD=passwordforquotegenerator
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5434:5432'
volumes:
  postgres:
      driver: local