version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - backend
  postgres:
    image: postgres:14.5-alpine3.16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=quote_generator
      - POSTGRES_USER=rafi
      - POSTGRES_PASSWORD=passwordforquotegenerator
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    networks:
      - backend
volumes:
  postgres:
    driver: local

networks:
  backend:
